import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const googleSans = localFont({
  src: [
    {
      path: '../public/assets/fonts/GoogleSans-Regular_0.ttf',
      weight: '400'
    },
    {
      path: '../public/assets/fonts/GoogleSans-Bold-v1.27.ttf',
      weight: '700'
    }
  ],
  variable: '--font-google'
})

export const metadata: Metadata = {
  title: "GDG Cloud Kolkata",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${googleSans.className}`}>
        <main className="flex flex-col items-start justify-start w-full max-w-screen-2xl mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
